# Generated by Django 3.0.1 on 2020-02-27 08:29

import budgetapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('tid', models.IntegerField(default=budgetapp.models.Income.number, primary_key=True, serialize=False, unique=True)),
                ('income_type', models.TextField()),
                ('description', models.TextField()),
                ('amount', models.FloatField()),
                ('recurring', models.BooleanField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('every', models.TextField()),
            ],
        ),
    ]
