# Generated by Django 3.0.1 on 2020-02-27 10:09

import budgetapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('tid', models.IntegerField(default=budgetapp.models.Expense.number, primary_key=True, serialize=False, unique=True)),
                ('expense_type', models.TextField()),
                ('description', models.TextField()),
                ('amount', models.FloatField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
