# Generated by Django 3.0.1 on 2020-02-27 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetapp', '0002_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='every',
            new_name='ondate',
        ),
        migrations.AddField(
            model_name='income',
            name='date_recurr',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='income',
            name='recurr',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='income',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
